### PR TITLE
Revert "Fix everything"

### PR DESCRIPTION
**Pull request by xDecider**
Reverts xDecider/Anti-Quest#1

yeaaa...
about that overhead

My version (0.8ms) :
unknown (my version)

Kirais Version (44.8m) :
unknown (Kirais Version)

### CODE REVIEW

**Comment by xKiraiChan** [comment]
45ms for code that small either means one of the following:
- You had stuff running in the background
  - Such as another application
  - Windows defender (or similar) scanning your mods
- You compiled in debug mode
- You are faking the results

Maybe you shouldn't have ever touched coding/client development.
You can't write code on your own and you have to copy it everything.
You were cool but this got to your head and now everyone sees you as a jackass.
image

**Comment by xKiraiChan** [comment]
If you need it stated in text, I do not see you as competent or at all respectable anymore.

**Comment by xDecider** [comment]
> 45ms for code that small either means one of the following:
> 
> * You had stuff running in the background
>   
>   * Such as another application
>   * Windows defender (or similar) scanning your mods
> * You compiled in debug mode
> * You are faking the results
> 
> Maybe you shouldn't have ever touched coding/client development. You can't write code on your own and you have to copy it everything. You were cool but this got to your head and now everyone sees you as a jackass. image

"I do not see you as competent or at all respectable"
Not only were you not respectable at all when you literally did a pull request which said "fix everything", you changed the entirety of the code to have no exception handling.
What happens if that method gets changed? The code will break, the user will be left clueless as to why. My version has something that atleast tells the user if it failed to patch the method in question.
If you need to trashtalk me saying "you shouldn't have ever touched coding" then that's pretty ironic, as your own "fixed code" literally creates more issues than mine.
Keep crying more over the internet.

**Comment by xKiraiChan** [comment]
> Not only were you not respectable at all

I have no reason to respect you when you copy and paste ***LITERALLY FUCKING EVERYTHING***

>  What happens if that method gets changed? The code will break, the user will be left clueless as to why. My version has something that atleast tells the user if it failed to patch the method in question.

A massive red error with your mod name will show up. That's a pretty clear indicator of an error. 

> to have no exception handling.

Your definition of exception handling is to silently drop the error and then leave the user clueless as to why the mod is not working. I would rather see an error than nothing.

> your own "fixed code" literally creates more issues than mine.

Let's have someone do an **actual** benchmark, if you look at the lowered code **at all** you will be able to clearly see yours is slower due to constantly jumping around and constantly entering and exiting try catch blocks.

Also, let's also keep in mind that your client was dropping an insurmountable amount of frames, meanwhile, I am known for making the most optimized client. You can keep making up whatever evidence you want.

>  Keep crying more over the internet.

You should reflect on the number of people that used to call you cool.
You are a ghost of your former self with no chance of any reclaimation.
Your ego has consumed you and you're too blind to realize it.

image
image

**Comment by abbe** [comment]
> > Not only were you not respectable at all
> 
> I have no reason to respect you when you copy and paste _**LITERALLY FUCKING EVERYTHING**_
> 
> > What happens if that method gets changed? The code will break, the user will be left clueless as to why. My version has something that atleast tells the user if it failed to patch the method in question.
> 
> A massive red error with your mod name will show up. That's a pretty clear indicator of an error.
> 
> > to have no exception handling.
> 
> Your definition of exception handling is to silently drop the error and then leave the user clueless as to why the mod is not working. I would rather see an error than nothing.
> 
> > your own "fixed code" literally creates more issues than mine.
> 
> Let's have someone do an **actual** benchmark, if you look at the lowered code **at all** you will be able to clearly see yours is slower due to constantly jumping around and constantly entering and exiting try catch blocks.
> 
> Also, let's also keep in mind that your client was dropping an insurmountable amount of frames, meanwhile, I am known for making the most optimized client. You can keep making up whatever evidence you want.
> 
> > Keep crying more over the internet.
> 
> You should reflect on the number of people that used to call you cool. You are a ghost of your former self with no chance of any reclaimation. Your ego has consumed you and you're too blind to realize it.
> 
> image image

Ever read the GitHub community guidelines (ctrl+f "Respect each other") or are you still furious over VRC developers not paying attention to you? I mean... you've faded to obscurity in an already dead "community" and you're just barely clinging on still by putting out ignorant comments like these.

You seem to go for the low blow of saying that Decider has a massive ego, yet just a few paragraphs above you write "I am known for making the most optimized client" (nobody even knows you, especially not for that. bold claim). 
Not only is this not even true at all, as your poor code was and probably still is one of the most useless stuff ever written for the game, you depended on MelonLoader which is already bad by itself.

It's time for you to drop your act and move on, he can do what he wants to learn.
You still use ML even though you hate it? Why so? Is it that you c+p and to this day still don't know how to make your own native tools / native "mod loader" for this game you love and play all day?

Your yes men are temporary. You should really check yourself and stop putting yourself in awkward situations.

**Comment by Umbra999** [comment]
Kirai never made anything original, a item orbit in unity im proud of you. He never was relevant and never will be.

**Comment by xKiraiChan** [comment]
> 

Despite this, you manage to be so low as to not even be able to write anything yourself and you have to copy it from Day?

**Comment by Umbra999** [comment]
> > Kirai never made anything original, a item orbit in unity im proud of you. He never was relevant and never will be.
> 
> Despite this, you manage to be so low as to not even be able to write anything yourself and you have to copy it from Day?

copy from day lmao xD day is not playing anymore for over 1 year. Day is a friend of mine and we shared our code when he worked on a client with me, but nice how clueless you are. I think i managed to get way more stuff done as you in the whole time while you are still stuck on your unity items. i never had anything public and turned more relevant as you with a public client and discord. You have no clue what i manage to get because i never had anything public for a reason that no names like you cant copy paste it - last time i respond to you, because you are just so fucking irrelevant im not gonna waste my time with you. Just let Decider upload to his github what he want? Nobody cares about your opinion if you dont already realised it. you litteraly wasting your time stalking githubs instead of doing anything productive by yourself. Stay mad noname.

**Comment by Umbra999** [comment]
> 

Only thing you were able to do is push a rat to your client loader and hit your users with it which trust you, kinda sad tbh

**Comment by xDecider** [comment]
THATS ENOUGH !!!!

**Pull request merged**
